version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_volume:/data
    ports:
      - 6379:6379

  adonis_app:
    container_name: adonis_app
    depends_on:
      - postgres
      - redis
    build:
      context: ./adonis
      dockerfile: ./Dockerfile
      target: dependencies
    ports:
      - ${PORT}:${PORT}
      - "9229:9229"
    env_file:
      - .env
    environment:
      - PG_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - ./adonis:/home/node/app
      # Uncomment the below line if you developing on MacOS
      #- /home/node/app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"

  react_app:
    container_name: react_app
    depends_on:
      - adonis_app
    build:
      context: ./react
      dockerfile: ./Dockerfile
    stdin_open: true
    volumes:
      - ./react/:/react
    ports:
      - "3000:3000"
    command: yarn dev

volumes:
  postgres_volume:
  redis_volume: