version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"

  redis:
    container_name: redis
    image: redis:latest
    volumes:
      - redis_volume:/data
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      REDIS_HOST: 127.0.0.1
    ports:
      - "6379:6379"

  nest_app:
    container_name: nest_app
    depends_on:
      - postgres
      - redis
    build:
      context: ./nestjs
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - ./nestjs:/usr/src/app
    env_file:
      - .env
    command: yarn start:dev
    ports:
      - '4000:4000'

  react_app:
    container_name: react_app
    depends_on:
      - nest_app
    build:
      context: ./react
      dockerfile: ./Dockerfile
    stdin_open: true
    volumes:
      - ./react/:/react
    ports:
      - "3000:3000"
    command: yarn dev

volumes:
  postgres_volume:
  mongo_volume:
  redis_volume:
